### ISSUE TITLE
TypeError: this._connectionResolver is null

### ISSUE THREAD

**Issue by startswithaj** [IcecaveLabs/overpass-websocket-client#4]
https://github.com/IcecaveLabs/overpass-websocket-client/blob/develop/src/connection/Connection.coffee#L97

Throws the error on this line `this._connectionResolver.reject(new Error(c.reason))`

Somehow the connectionResolver is already null before it can reject it.

**Comment by jmalloc** [comment]
FYI @ezzatron

**Comment by startswithaj** [comment]
I've looked into this pretty heavily.

Couldn't find a pathway where this should occur.

**Comment by jmalloc** [comment]
Repo is being archived.
